### ISSUE TITLE
Expansion scenarios for the Arctic: MOSAiC and/or NSA

### ISSUE THREAD

**Issue by wgustafson** [ARM-DOE/lasso-public#2]
This thread is for discussing opportunities to expand LASSO to do simulations in the Arctic, either for the [MOSAiC](https://www.arm.gov/research/campaigns/amf2019mosaic) field campaign or at the [North Slope of Alaska (NSA)](https://www.arm.gov/capabilities/observatories/nsa) atmospheric observatory. Some background information can be found in the [associated blog entry](https://www.arm.gov/news/blog/post/52113). Additional discussion threads will be created as the [LASSO Expansion blog series](https://www.arm.gov/news-events/search?news-category%5B0%5D%5B0%5D=post&news-category%5B1%5D%5B0%5D=LASSO) focuses on additional sites.

How would you use LASSO simulations in the Arctic? What types of research would they benefit and how would you apply them? How would you configure a high-resolution model at NSA or for MOSAiC to complement ARM's observations? What additional observations are needed? How would you deal with handling the coastline at Utqiaġvik?

Note ARM's [Comment Policy](https://github.com/ARM-DOE/lasso-public/wiki/Comment-Policy).

**Comment by eroesler** [comment]
Just repeating the text for #3  "For the MOSAiC field campaign, I would like to pursue a location-adaptive grid nested in a larger regional model either online or offline.  Uninformed question here, but would deep convection be needed for MOSAiC?"

For the coastline, can we make a binary domain when it seasonally matters?

**Comment by wgustafson** [comment]
The types of clouds I have envisioned for the Arctic are more layered and stratus-like. However, I expect there might be more convective types over leads. In configuring the model, the main issues would be how tall they get and if they would require a larger horizontal domain. I am still learning about the Arctic, as I have always worked more equatorward in the past. We will need to look into this.

Regarding the coastline, when using periodic boundaries it would be pretty easy to setup the LES to either have ocean or ice for the bottom boundary depending on the conditions. If one uses a nested approach, we could pull the lower boundary from the mother nest, which presumably would have spatially dependent sea ice and an interactive soil model.

**Comment by eroesler** [comment]
That makes good sense, thanks for explaining!   

The scope of getting everything properly represented at NSA or MOSAiC seems daunting from the boundary to the stratified atmosphere.   What would be a priority?  Cloud macrophyiscs or microphysics?   Including aerosols?  Surface variability and seasonality?  With LASSO, there was a narrowing of scope with only certain convective cases.  Could scope be narrowed here, too? I would like to see a dataset (value added product) that has smallish error bars for cloud speciation that could be used for  GCMS.

**Comment by MatthewShupe** [comment]
Sorry it has taken so long to write....But here are some perspectives.

First, to the question asked before, I do not believe there would be a need for representing deep convection.  There is shallow convection from heat sources like leads, but not deep convection.  And surely the focus would be more on the stratified cloudy environment.

As for how LASSO would be useful:  Here I specifically speak to the MOSAiC example, although to some degree these points are also true for Barrow/North Slope.  My main interests are with regard to (1) microphysical processes and specifically the interaction of liquid and ice towards determining the ultimate phase partitioning of Arctic clouds, (2) the interactions of Arctic clouds with large-scale advection and the local (variable) surface.... i.e., understanding the balance of external forcing vs. local processes for determining cloud formation and longevity, (3) the sensitivities of Arctic clouds to aerosol amounts, vertical distribution, and processes.   All three of these areas are of great interest in Arctic cloud studies, all three speak to areas wherein ARM makes very relevant measurements, and all three are at a state where major progress can be made.

For examining these processes, there would have to be some significant thought and planning. Simulations would have to rely on constraining certain parts of the system (i.e., idealized surface representation) to examine other parts. For example, a set of simulations could be done that specifies different amounts of open water (and surface heat fluxes) to examine how these impact the evolution of cloud structure that is otherwise driven by the large-scale advection of moisture.  Lots of possible ideas for similar types of simulations.  The important part, and a great thing about LASSO, is that there could be a lot of these simulations.  Arctic cloud research has been hindered by the fact that most model studies have focused on a single case..... (how representative a single "golden day" case is of broader processes has always been a big question).

One interesting thing about MOSAiC is that there will be multiple observations at various times of the year.  The ARM measurements on Polarstern will be extremely valuable.  There will also be ARM-like measurements at NyAlesund on Svalbard that can provide useful perspectives upstream under southerly flow regimes. At two different times of the year there will also be aircraft missions flying between Svalbard and the MOSAiC site that could look at the evolution of airmasses (cloud properties, atmospheric profiles, etc.) along trajectories that go towards or away from the MOSAiC site.  These intensive observing periods offer enhanced spatial information that will be useful for evaluating the simulations.

**Comment by drfeldman2012** [comment]
I'm delighted to read about the discussion so far and to have the opportunity to contribute, especially since it appears from this thread that there is interest in moving forward on a high-latitude LASSO effort. I would like raise a few points which argue for a prioritization of LASSO simulations over MOSAiC .

First, LASSO simulations could enable a more robust comparison of MOSAiC radiometric observations against polar-orbiting satellite products such as CERES surface fluxes.  It could be pretty hard to do this comparison otherwise.

Second, these simulations would enable a more-informed interpolation between the distributed network of stations to understand the value of those data relative to the observations on the ship.

Third, LASSO might enable flexible science over MOSAiC.  That is, LASSO could help establish the information content of the observations during the campaign, such that when there is flexibility in terms of observational choices, researchers can use LASSO to choose optimal observational strategies while out on the ice.

**Comment by wgustafson** [comment]
Closing this issue on GitHub. Folks interested in contributing further thoughts should post a comment in the LASSO category on <https://discourse.arm.gov/c/lasso/lasso-general/11>.
