### ISSUE TITLE
Expansion scenarios for clear-air turbulence

### ISSUE THREAD

**Issue by wgustafson** [ARM-DOE/lasso-public#4]
This thread is for discussing opportunities to expand [LASSO](https://www.arm.gov/capabilities/modeling/lasso) to do simulations of clear-air turbulence at one of the U.S. Department of Energy [Atmospheric Radiation Measurement](https://www.arm.gov/) facility's atmospheric observatories. Some background information can be found in the [associated blog entry](https://www.arm.gov/news/blog/post/52603). Other themes for expansion scenarios are discussed in the [LASSO Expansion blog series](https://www.arm.gov/news-events/search?news-category%5B0%5D%5B0%5D=post&news-category%5B1%5D%5B0%5D=LASSO).

How would you configure routine simulations of clear-air turbulence to complement ARM's measurements? How would you prioritize this category in relation to other LASSO expansion scenarios, such as those discussed in previous posts in this series? What observations would you want included in the data bundle? What new observations would ARM need to add to complement and/or evaluate the LES? What science questions would you like the simulations to support?

Note ARM's [Comment Policy](https://github.com/ARM-DOE/lasso-public/wiki/Comment-Policy).

**Comment by eroesler** [comment]
Hi @wgustafson!  
That would be a very interesting expansion!   Clear Air Turbulence (CAT) would be a first-order asset to ARM to model.   Modeling high-resolution, near -DNS turbulence with a bundle of subgrid scale parameterizations optimized for specific observations could reveal so much about bias, assumptions, and missing information.   CAT might be one of the few scenarios the Earth's atmosphere gives us scientists to reduce the number of variables in the "experiment" (a.k.a., the model).  Modelers have the ability to simplify by neglecting water in a liquid or solid forms.   Deeper vertical models from the surface to the top-of-atmosphere on clear, sunny days, with CAT could also be developed instead of limiting the vertical lid.  The soundings, VAP interpolated soundings, and even rocket soundings into the higher levels of the atmosphere could be used as data to evaluate the model.   I'm imagining a very unique LES configuration for this :)

**Comment by davidturner53** [comment]
I believe that ARM has the ability to make major contributions to characterizing turbulence in the PBL, and how it changes over the diurnal cycle, interacts with the land surface, the importance of entrainment, and more.  In many ways, the current SGP site is very well suited to tackle this problem already; however, we just need to identify cases without clouds, create the forcing, and make the LES runs.  Thijs Heus has performed a few of these runs already using different LES cores, and found markedly different turbulence profiles (e.g., 2nd order moments of w) even though we tried to force all of the models the same way.  Is this a numerics issue (bug), something associated with the sub grid-scale parameterizations, or something else?  It does seem that this is a "walk before you run" exercise; if we are unable to characterize clear air turbulent motions in an LES properly, how can we be sure that our sims in cloudy conditions are telling us anything useful?

**Comment by wgustafson** [comment]
Closing this issue on GitHub. Folks interested in contributing further thoughts should post a comment in the LASSO category on <https://discourse.arm.gov/c/lasso/lasso-general/11>.
